plone:
  image: plone-eea-common
  ports:
  - "8081:80"
  links:
  - postgres
  - memcached
  - postfix
  volumes:
  - buildout.cfg:/opt/zope/buildout.cfg
  environment:
  - PLONE_APP_ASYNC=single_db_instance

async:
  image: plone-eea-common
  ports:
  - "8082:80"
  links:
  - postgres
  - memcached
  - postfix
  volumes:
  - buildout.cfg:/opt/zope/buildout.cfg
  environment:
  - PLONE_APP_ASYNC=single_db_worker

postgres:
  image: eeacms/postgres
  environment:
  - POSTGRES_DBNAME=datafs
  - POSTGRES_DBUSER=zope
  - POSTGRES_DBPASS=zope
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=secret

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048

postfix:
  image: eeacms/postfix
  environment:
  - MTP_HOST=eea.europa.eu

data:
  image: busybox
  volumes:
  - /var/lib/postgresql/data
  command: chown -R 999:999 /var/lib/postgresql/data
