plone:
  image: eeacms/plone-eea-common-relstorage:5.3
  links:
  - postgres
  - memcached
  - postfix
  environment:
  - PLONE_APP_ASYNC=single_db_instance
  - BUILDOUT_REBUILD=true

async:
  image: eeacms/plone-eea-common-relstorage:5.3
  links:
  - postgres
  - memcached
  - postfix

postgres:
  image: eeacms/postgres
  environment:
  - POSTGRES_DBNAME=datafs
  - POSTGRES_DBUSER=zope
  - POSTGRES_DBPASS=zope
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=secret
  volumes_from:
  - data

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048

postfix:
  image: eeacms/postfix
  environment:
  - MTP_HOST=eea.europa.eu

data:
  image: busybox
  volumes:
  - /var/lib/postgresql/data
  command: chown -R 999:999 /var/lib/postgresql/data
