plone:
  image: eeacms/plone-eea-common-zeoclient
  links:
  - zeoserver
  - memcached
  - postfix
  environment:
  - PLONE_APP_ASYNC=single_db_instance
  - BUILDOUT_REBUILD=true

async:
  image: eeacms/plone-eea-common-zeoclient
  links:
  - zeoserver
  - memcached
  - postfix

zeoserver:
  image: eeacms/zeoserver
  volumes_from:
  - data

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048

postfix:
  image: eeacms/postfix
  environment:
  - MTP_HOST=eea.europa.eu

data:
  image: busybox
  volumes:
  - /opt/zeoserver/var/filestorage
  - /opt/zeoserver/var/blobstorage
  command: chown -R 500:500 /opt/zeoserver/var
