plone:
  image: eeacms/plone-eea-common:5.2
  ports:
  - "8081:80"
  links:
  - zeoserver
  - memcached
  - postfix
  volumes:
  - buildout.cfg:/opt/zope/buildout.cfg
  environment:
  - PLONE_APP_ASYNC=single_db_instance
  - ZEO_CLIENT=True

async:
  image: eeacms/plone-eea-common:5.2
  ports:
  - "8082:80"
  links:
  - zeoserver
  - memcached
  - postfix
  volumes:
  - buildout.cfg:/opt/zope/buildout.cfg
  environment:
  - PLONE_APP_ASYNC=single_db_worker
  - ZEO_CLIENT=True

zeoserver:
  image: eeacms/zeoserver
  volumes_from:
  - data

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048

postfix:
  image: eeacms/postfix
  environment:
  - MTP_HOST=eea.europa.eu

data:
  image: busybox
  volumes:
  - /opt/zeoserver/var/filestorage
  - /opt/zeoserver/var/blobstorage
  command: chown -R 500:500 /opt/zeoserver/var
